version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - DB_PASSWORD=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.7.2
    container_name: pet-adoption-db
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - PF_CLIENT_ID=${PF_CLIENT_ID}
      - PF_CLIENT_SECRET=${PF_CLIENT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
    command: >
      bash -c "
      airflow db upgrade &&
      python3 /opt/airflow/scripts/createConnections.py &&
      airflow standalone"
    depends_on:
      - postgres

volumes:
  postgres_data:
